/*Print out*/
function PrintFunction(MenuID,tableID) {
    
    debugger
    var $contextMenu = $(MenuID);
    $contextMenu.hide();

    var divToPrint = document.getElementById(tableID);
    newWin = window.open("");
    newWin.document.write(divToPrint.outerHTML);
    newWin.print();
    newWin.close();
   

   
}



function PrintSheetFunction(tableID)
{
    debugger
    var divToPrint = document.getElementById(tableID);
    newWin = window.open("");
    newWin.document.write(divToPrint.outerHTML);
    newWin.print();
    newWin.close();
}



function PrintforReport(title, tableID) {
    debugger
    const headerContent = `
      <div style="display: flex; justify-content: space-between; align-items: center; margin-top: 20px; padding-bottom: 10px; border-bottom: 2px solid #000;">
            <!-- Company Logo and Title -->
            <div style="display: flex; align-items: center;">
                <img src="/admin_assets/images/comapanylogo.jpg" alt="Inspection Pro" style="height: 70px; margin-right: 10px;">
                <h1 style="margin: 0; font-size: 28px; color: #333;">Inspection Pro</h1>
            </div>

            <!-- Date -->
            <div>
                <p style="margin: 0; font-size: 14px; color: #666;">Date: ${new Date().toLocaleDateString()}</p>
            </div>
        </div>

        `;
    const footerContent = `
            <div style="text-align: center; margin-top: 20px; border-top: 2px solid #000; padding-top: 10px;">
                <p style="margin: 0; font-size: 14px; color: #666;">Generated by Inspection Pro</p>
                <p style="margin: 0; font-size: 12px; color: #aaa;">Confidential Report - ${new Date().getFullYear()}</p>
            </div>
        `;
    $(tableID).printThis(
        {
            pageTitle: title,
            importStyle: true,
            importCSS: true,
            header: headerContent,
            footer: footerContent,
            printContainer: true,
            doctypeString: '<!DOCTYPE html>',
            beforePrint: null,
            afterPrint: null,
            formValues: true

        });

}

/*end Print out*/
//PDF

//PDF

/*Excel sheet*/
function ExcelFuncntion(tableID,ID,FileName) {

    debugger
    //var $contextMenu = $(MenuID);
    //$contextMenu.hide();


    var tab_text = '<html xmlns:x="urn:schemas-microsoft-com:office:excel">';
    tab_text = tab_text + '<head><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet>';

    tab_text = tab_text + '<x:Name>Requisition Report</x:Name>';

    tab_text = tab_text + '<x:WorksheetOptions><x:Panes></x:Panes></x:WorksheetOptions></x:ExcelWorksheet>';
    tab_text = tab_text + '</x:ExcelWorksheets></x:ExcelWorkbook></xml></head><body>';

    tab_text = tab_text + "<table border='1px'>";
    tab_text = tab_text + $(tableID).html();
    tab_text = tab_text + '</table></body></html>';

    var data_type = 'data:application/vnd.ms-excel';

    var ua = window.navigator.userAgent;
    var msie = ua.indexOf("MSIE");

    if (msie > 0 || !!navigator.userAgent.match(/Trident.*rv\:11\./)) {
        if (window.navigator.msSaveBlob) {
            var blob = new Blob([tab_text], {
                type: "application/csv;charset=utf-8;"
            });
            navigator.msSaveBlob(blob, 'Faizan.xls');
        }
    }
    else
    {
        $(ID).attr('href', data_type + ', ' + encodeURIComponent(tab_text));
        $(ID).attr('download', FileName);

       
       
    }

}
/*End Excel sheet*/